language: android
sudo: required
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra
script: ./gradlew clean assemble test
before_install:
- openssl aes-256-cbc -K $encrypted_ee32c96311e1_key -iv $encrypted_ee32c96311e1_iv
  -in gradle.properties.enc -out gradle.properties -d
